spring:
  servlet:
    multipart:
      max-file-size: 1GB
  mvc:
    log-resolved-exception: false
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
  datasource:
    url: ${DB_URL}?escapeSyntaxCallMode=callIfNoReturn
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 6000
      maximum-pool-size: 100
      minimum-idle: 10
  jpa:
    open-in-view: false

logging:
  level:
    jp:
      taira:
        sample: debug
    web: info
    sql: debug
